//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mraznicka.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mraznicka.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ano.
        /// </summary>
        internal static string ano {
            get {
                return ResourceManager.GetString("ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datumvytvorenia.
        /// </summary>
        internal static string datumvytvorenia {
            get {
                return ResourceManager.GetString("datumvytvorenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detailmiestnosti.
        /// </summary>
        internal static string detailmiestnosti {
            get {
                return ResourceManager.GetString("detailmiestnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detailpolozky.
        /// </summary>
        internal static string detailpolozky {
            get {
                return ResourceManager.GetString("detailpolozky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detailpozicie.
        /// </summary>
        internal static string detailpozicie {
            get {
                return ResourceManager.GetString("detailpozicie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detailtovaru.
        /// </summary>
        internal static string detailtovaru {
            get {
                return ResourceManager.GetString("detailtovaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailný popis zariadenia.
        /// </summary>
        internal static string detailzariadenia {
            get {
                return ResourceManager.GetString("detailzariadenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ean.
        /// </summary>
        internal static string ean {
            get {
                return ResourceManager.GetString("ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ean sa nepouziva.
        /// </summary>
        internal static string eansanepouziva {
            get {
                return ResourceManager.GetString("eansanepouziva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emptytag.
        /// </summary>
        internal static string emptytag {
            get {
                return ResourceManager.GetString("emptytag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirácia.
        /// </summary>
        internal static string expiracia {
            get {
                return ResourceManager.GetString("expiracia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiracia (dni).
        /// </summary>
        internal static string expiraciadni {
            get {
                return ResourceManager.GetString("expiraciadni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expresspull.
        /// </summary>
        internal static string expresspull {
            get {
                return ResourceManager.GetString("expresspull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expresspush.
        /// </summary>
        internal static string expresspush {
            get {
                return ResourceManager.GetString("expresspush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatingtagoperationsucceessful.
        /// </summary>
        internal static string formatingtagoperationsucceessful {
            get {
                return ResourceManager.GetString("formatingtagoperationsucceessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hmotnost ( g ).
        /// </summary>
        internal static string hmotnost {
            get {
                return ResourceManager.GetString("hmotnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        internal static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kategoria.
        /// </summary>
        internal static string kategoria {
            get {
                return ResourceManager.GetString("kategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to licencnecislo.
        /// </summary>
        internal static string licencnecislo {
            get {
                return ResourceManager.GetString("licencnecislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manual.
        /// </summary>
        internal static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manualnyvyber.
        /// </summary>
        internal static string manualnyvyber {
            get {
                return ResourceManager.GetString("manualnyvyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to musiexistovataspomjedenzaznam.
        /// </summary>
        internal static string musiexistovataspomjedenzaznam {
            get {
                return ResourceManager.GetString("musiexistovataspomjedenzaznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naozajchcetevymazatzaznam.
        /// </summary>
        internal static string naozajchcetevymazatzaznam {
            get {
                return ResourceManager.GetString("naozajchcetevymazatzaznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazov.
        /// </summary>
        internal static string nazov {
            get {
                return ResourceManager.GetString("nazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nfcisdissabled.
        /// </summary>
        internal static string nfcisdissabled {
            get {
                return ResourceManager.GetString("nfcisdissabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nfcisnotavailable.
        /// </summary>
        internal static string nfcisnotavailable {
            get {
                return ResourceManager.GetString("nfcisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie.
        /// </summary>
        internal static string nie {
            get {
                return ResourceManager.GetString("nie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niejemoznevymazatzaznam.
        /// </summary>
        internal static string niejemoznevymazatzaznam {
            get {
                return ResourceManager.GetString("niejemoznevymazatzaznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notagfound.
        /// </summary>
        internal static string notagfound {
            get {
                return ResourceManager.GetString("notagfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novamiestnost.
        /// </summary>
        internal static string novamiestnost {
            get {
                return ResourceManager.GetString("novamiestnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novapolozka.
        /// </summary>
        internal static string novapolozka {
            get {
                return ResourceManager.GetString("novapolozka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novapozicia.
        /// </summary>
        internal static string novapozicia {
            get {
                return ResourceManager.GetString("novapozicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové zariadenie.
        /// </summary>
        internal static string novezariadenie {
            get {
                return ResourceManager.GetString("novezariadenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novytovar.
        /// </summary>
        internal static string novytovar {
            get {
                return ResourceManager.GetString("novytovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oznam.
        /// </summary>
        internal static string oznam {
            get {
                return ResourceManager.GetString("oznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        internal static string popis {
            get {
                return ResourceManager.GetString("popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popispoziciadetail.
        /// </summary>
        internal static string popispoziciadetail {
            get {
                return ResourceManager.GetString("popispoziciadetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popispozicialist.
        /// </summary>
        internal static string popispozicialist {
            get {
                return ResourceManager.GetString("popispozicialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popispoziciavytvorenie.
        /// </summary>
        internal static string popispoziciavytvorenie {
            get {
                return ResourceManager.GetString("popispoziciavytvorenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popistovardetail.
        /// </summary>
        internal static string popistovardetail {
            get {
                return ResourceManager.GetString("popistovardetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popistovarvytvorenie.
        /// </summary>
        internal static string popistovarvytvorenie {
            get {
                return ResourceManager.GetString("popistovarvytvorenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popistovarzoznam.
        /// </summary>
        internal static string popistovarzoznam {
            get {
                return ResourceManager.GetString("popistovarzoznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popisvlozenie.
        /// </summary>
        internal static string popisvlozenie {
            get {
                return ResourceManager.GetString("popisvlozenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popisvyber.
        /// </summary>
        internal static string popisvyber {
            get {
                return ResourceManager.GetString("popisvyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popiszariadeniedetail.
        /// </summary>
        internal static string popiszariadeniedetail {
            get {
                return ResourceManager.GetString("popiszariadeniedetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popiszariadenievytvorenie.
        /// </summary>
        internal static string popiszariadenievytvorenie {
            get {
                return ResourceManager.GetString("popiszariadenievytvorenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popiszariadeniezoznam.
        /// </summary>
        internal static string popiszariadeniezoznam {
            get {
                return ResourceManager.GetString("popiszariadeniezoznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poslednepouzite.
        /// </summary>
        internal static string poslednepouzite {
            get {
                return ResourceManager.GetString("poslednepouzite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozícia.
        /// </summary>
        internal static string pozicia {
            get {
                return ResourceManager.GetString("pozicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poznamka.
        /// </summary>
        internal static string poznamka {
            get {
                return ResourceManager.GetString("poznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehľad.
        /// </summary>
        internal static string prehlad {
            get {
                return ResourceManager.GetString("prehlad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehľad s výberom.
        /// </summary>
        internal static string prehlad_main {
            get {
                return ResourceManager.GetString("prehlad_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pridat.
        /// </summary>
        internal static string pridat {
            get {
                return ResourceManager.GetString("pridat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recordcantbenull.
        /// </summary>
        internal static string recordcantbenull {
            get {
                return ResourceManager.GetString("recordcantbenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suflik.
        /// </summary>
        internal static string suflik {
            get {
                return ResourceManager.GetString("suflik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        internal static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagid.
        /// </summary>
        internal static string tagid {
            get {
                return ResourceManager.GetString("tagid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taginfo.
        /// </summary>
        internal static string taginfo {
            get {
                return ResourceManager.GetString("taginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag sa nepouziva.
        /// </summary>
        internal static string tagsanepouziva {
            get {
                return ResourceManager.GetString("tagsanepouziva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tovar.
        /// </summary>
        internal static string tovar {
            get {
                return ResourceManager.GetString("tovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ulozit.
        /// </summary>
        internal static string ulozit {
            get {
                return ResourceManager.GetString("ulozit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupportedtag.
        /// </summary>
        internal static string unsupportedtag {
            get {
                return ResourceManager.GetString("unsupportedtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userhascancelnfcsession.
        /// </summary>
        internal static string userhascancelnfcsession {
            get {
                return ResourceManager.GetString("userhascancelnfcsession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uvodnastranka.
        /// </summary>
        internal static string uvodnastranka {
            get {
                return ResourceManager.GetString("uvodnastranka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.1.
        /// </summary>
        internal static string verzia {
            get {
                return ResourceManager.GetString("verzia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vloženie.
        /// </summary>
        internal static string vlozenie {
            get {
                return ResourceManager.GetString("vlozenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlozeniemanualne.
        /// </summary>
        internal static string vlozeniemanualne {
            get {
                return ResourceManager.GetString("vlozeniemanualne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlozeniepomocouean.
        /// </summary>
        internal static string vlozeniepomocouean {
            get {
                return ResourceManager.GetString("vlozeniepomocouean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlozeniepomocoutagu.
        /// </summary>
        internal static string vlozeniepomocoutagu {
            get {
                return ResourceManager.GetString("vlozeniepomocoutagu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výber.
        /// </summary>
        internal static string vyber {
            get {
                return ResourceManager.GetString("vyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hľadanie s výberom.
        /// </summary>
        internal static string vyber_main {
            get {
                return ResourceManager.GetString("vyber_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vyberpomocouean.
        /// </summary>
        internal static string vyberpomocouean {
            get {
                return ResourceManager.GetString("vyberpomocouean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vyberpomocoutagu.
        /// </summary>
        internal static string vyberpomocoutagu {
            get {
                return ResourceManager.GetString("vyberpomocoutagu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vymazaniezaznamu.
        /// </summary>
        internal static string vymazaniezaznamu {
            get {
                return ResourceManager.GetString("vymazaniezaznamu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writingtagisnotsupportedonthisdevice.
        /// </summary>
        internal static string writingtagisnotsupportedonthisdevice {
            get {
                return ResourceManager.GetString("writingtagisnotsupportedonthisdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writingtagoperationsuccessful.
        /// </summary>
        internal static string writingtagoperationsuccessful {
            get {
                return ResourceManager.GetString("writingtagoperationsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadajteexpiraciu.
        /// </summary>
        internal static string zadajteexpiraciu {
            get {
                return ResourceManager.GetString("zadajteexpiraciu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadajtehmotnost.
        /// </summary>
        internal static string zadajtehmotnost {
            get {
                return ResourceManager.GetString("zadajtehmotnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadajtelicencnecislo.
        /// </summary>
        internal static string zadajtelicencnecislo {
            get {
                return ResourceManager.GetString("zadajtelicencnecislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadajtenazov.
        /// </summary>
        internal static string zadajtenazov {
            get {
                return ResourceManager.GetString("zadajtenazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento údaj je povinný.
        /// </summary>
        internal static string zadajtepopis {
            get {
                return ResourceManager.GetString("zadajtepopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadajtepoznamku.
        /// </summary>
        internal static string zadajtepoznamku {
            get {
                return ResourceManager.GetString("zadajtepoznamku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zapisnatag.
        /// </summary>
        internal static string zapisnatag {
            get {
                return ResourceManager.GetString("zapisnatag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zariadenie.
        /// </summary>
        internal static string zariadenie {
            get {
                return ResourceManager.GetString("zariadenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamexistuje.
        /// </summary>
        internal static string zaznamexistuje {
            get {
                return ResourceManager.GetString("zaznamexistuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zmazat.
        /// </summary>
        internal static string zmazat {
            get {
                return ResourceManager.GetString("zmazat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam položiek.
        /// </summary>
        internal static string zoznampoloziek {
            get {
                return ResourceManager.GetString("zoznampoloziek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam pozícií.
        /// </summary>
        internal static string zoznampozicii {
            get {
                return ResourceManager.GetString("zoznampozicii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam kategórií.
        /// </summary>
        internal static string zoznamtovarov {
            get {
                return ResourceManager.GetString("zoznamtovarov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoznam zariadení.
        /// </summary>
        internal static string zoznamzariadeni {
            get {
                return ResourceManager.GetString("zoznamzariadeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zrusit.
        /// </summary>
        internal static string zrusit {
            get {
                return ResourceManager.GetString("zrusit", resourceCulture);
            }
        }
    }
}
